"""Auto-generate and persist secrets for personal-mode installs.

Personal installs need a stable `credential_encryption_key` (so sealed LLM
credentials survive restarts) and a `chat_figure_signing_secret`. Both are
generated once and written to `$AI_ALMANAC_DATA_DIR/secrets.env` so they
survive data-dir mounts without leaking into env vars or config files that
operators might commit.

Layer order in reload_settings():
  defaults < secrets.env < config.yaml < DB overlay < env vars

secrets.env sits below config.yaml so operator-set values stay authoritative.
Env vars always win (handled inside _apply_overlay).
"""

from __future__ import annotations

import base64
import logging
import os
import secrets
import stat
from contextlib import suppress

from ai_almanac.locking import file_lock
from ai_almanac.paths import data_root, secrets_env_path

logger = logging.getLogger(__name__)

# Maps settings field name → generator callable.
_MANAGED_SECRETS: dict[str, object] = {
    "credential_encryption_key": lambda: base64.urlsafe_b64encode(os.urandom(32)).decode(),
    "chat_figure_signing_secret": lambda: secrets.token_urlsafe(32),
}

# Maps the env-var name (upper) → settings field name (lower).
_ENV_NAME_MAP: dict[str, str] = {
    "CREDENTIAL_ENCRYPTION_KEY": "credential_encryption_key",
    "CHAT_FIGURE_SIGNING_SECRET": "chat_figure_signing_secret",
}

# Default value for each managed field — skip generation when the effective
# value is already non-default (operator supplied it via config.yaml or DB).
_DEFAULTS: dict[str, str] = {
    "credential_encryption_key": "",
    "chat_figure_signing_secret": "dev-chat-figure-secret",
}

_SECRETS_HEADER = "# generated by ai-almanac — do not commit or share\n"


def load_secrets_file() -> dict[str, str]:
    """Parse secrets.env and return managed keys only, keyed by settings field name.

    Missing file → {}. Group/other-readable file → warn and chmod 0600.
    """
    path = secrets_env_path()
    if not path.exists():
        return {}

    try:
        mode = path.stat().st_mode
        if mode & (stat.S_IRGRP | stat.S_IROTH):
            logger.warning(
                "secrets.env at %s is group/other-readable; tightening permissions to 0600",
                path,
            )
            path.chmod(0o600)
    except OSError:
        pass

    result: dict[str, str] = {}
    try:
        for raw in path.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            field = _ENV_NAME_MAP.get(key)
            if field:
                result[field] = value
    except OSError:
        pass
    return result


def ensure_local_secrets() -> bool:
    """Generate missing managed secrets and persist them to secrets.env.

    Must be called with deployment_mode == "personal" — callers are responsible
    for checking this before calling. Returns True if anything was written so
    the caller can reload settings to pick up the new values.

    Skips a field if:
      (a) the corresponding env var is set (env wins),
      (b) the field is already in secrets.env, or
      (c) the effective settings value is non-default (operator supplied it).
    """
    lock_path = data_root() / "secrets.env.lock"
    with file_lock(lock_path, message="waiting for secrets.env lock…"):
        return _ensure_local_secrets_locked()


def _ensure_local_secrets_locked() -> bool:
    from ai_almanac.settings import settings

    existing = load_secrets_file()
    to_write: dict[str, str] = dict(existing)
    wrote_anything = False

    for field, generator in _MANAGED_SECRETS.items():
        env_var = field.upper()
        # (a) env var set — skip
        if env_var in os.environ:
            continue
        # (b) already in file — skip
        if field in existing:
            continue
        # (c) effective value is non-default — skip (operator supplied it)
        effective = getattr(settings, field, _DEFAULTS.get(field, ""))
        if effective != _DEFAULTS.get(field, ""):
            continue
        to_write[field] = generator()  # type: ignore[operator]
        wrote_anything = True

    if not wrote_anything:
        return False

    _write_secrets_file(to_write)
    return True


def _write_secrets_file(values: dict[str, str]) -> None:
    path = secrets_env_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    # Reverse the field→env-var map for writing.
    field_to_env = {v: k for k, v in _ENV_NAME_MAP.items()}

    lines = [_SECRETS_HEADER]
    for field, value in values.items():
        env_var = field_to_env.get(field, field.upper())
        lines.append(f"{env_var}={value}\n")

    content = "".join(lines)
    tmp_path = path.parent / f".secrets.env.tmp-{os.getpid()}"
    try:
        fd = os.open(str(tmp_path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            os.write(fd, content.encode())
        finally:
            os.close(fd)
        os.replace(str(tmp_path), str(path))
    except Exception:
        with suppress(OSError):
            tmp_path.unlink(missing_ok=True)
        raise
